---
apiVersion: v1
kind: Namespace
metadata:
  name: exo3
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: exo3-d
  namespace: exo3

spec:
  replicas: 1
  selector:
    matchLabels:
      app: exo3

  template:
    metadata:
      labels:
        app: exo3
    spec:
      containers:
      - name: exo3-c
        image: gotzo/exo3:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: exo3-svc
  namespace: exo3

spec:
  type: NodePort
  selector:
    app: exo3
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30042
      protocol: TCP
---

apiVersion: v1
kind: Pod
metadata:
  name: mariadb
  labels:
    app: mariadb

spec:
  containers:
  - name: mariadb-c
    image: mariadb:10
    env:
    - name: MARIADB_ROOT_PASSWORD
      value: "juve"
    - name: MARIADB_DATABASE
      value: "exo3"
    - name: MARIADB_USER
      value: "delpiero"
    - name: MARIADB_PASSWORD
      value: "juve"
    ports:
    - containerPort: 3306

    volumeMounts:
      - name: mariadb-v
        mountPath: /var/lib/mysql

  volumes:
  - name: mariadb-v
    persistentVolumeClaim:
      claimName: mariadb-v
---

apiVersion: v1
kind: Service
metadata:
  namespace : exo3
  name: mariadb-svc
  labels:
    app: mariadb
spec:
  ports:
    - port: 3306
  selector:
    app: mariadb
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: exo3
  name: mariadb-v
  labels:
    app: mariadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 42Gi
...
